apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deg-appset-argocd
spec:
  destination:
    namespace: og-appset
    server: 'https://kubernetes.default.svc'
  source:
    path: deployment/openshift
    repoURL: 'https://github.com/gayeomar/deg-springboot-ref/02_tracing/service-03/deploy/argocd'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      automated:
        prune: false
        selfHeal: false
      prune: true
      selfHeal: true
