apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: service-03
  name: service-03
spec:
  path:
    /
  port:
    targetPort: http
  to:
    kind: Service
    name: service-03
    weight: 100
